<a href="https://colab.research.google.com/github/Narrayane/02_Aprendendo_a_fazer_ETL_Alura/blob/main/03_Pandas_Transformacao__Pr%C3%A1tica2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Projeto desafio 2: administração de condomínios**

A administração de condomínios é uma tarefa que requer muita atenção e organização. Entre as diversas responsabilidades da gestão está o recebimento dos aluguéis dos locatários. Para garantir uma boa saúde financeira do empreendimento, é fundamental que esses pagamentos sejam feitos de forma regular e pontual. No entanto, sabemos que nem sempre isso acontece.

Pensando nisso, proponho um desafio de tratamento de dados com o objetivo de analisar o atraso no pagamento de aluguéis no condomínio de alguns moradores. Disponibilizo a base de dados dados_locacao_imoveis.json, que contém informações sobre o apartamento dos locatários, o dia acordado para o pagamento do aluguel, o dia da efetivação do pagamento de aluguel e o valor do aluguel.

Com essas informações, o desafio do projeto 2: administração de condomínios será similar ao desafio do projeto 1, abrir a base de dados com Pandas e aplicar o json_normalize no DataFrame.

In [1]:
import pandas as pd

In [2]:
# Ler o arquivo json com read_json
dados = pd.read_json('/content/dados_locacao_imoveis.json')
dados.head()

                                       dados_locacao
0  {'apartamento': 'A101 (blocoAP)', 'datas_combi...
1  {'apartamento': 'A102 (blocoAP)', 'datas_combi...
2  {'apartamento': 'B201 (blocoAP)', 'datas_combi...
3  {'apartamento': 'B202 (blocoAP)', 'datas_combi...
4  {'apartamento': 'C301 (blocoAP)', 'datas_combi...

In [3]:
# Aplicar json_normalize na coluna dados_locacao
dados = pd.json_normalize(dados['dados_locacao'])
dados.head()

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),"[01/06/2022, 01/07/2022]","[05/06/2022, 03/07/2022]","[$ 1000,0 reais, $ 2500,0 reais]"
1,A102 (blocoAP),"[02/06/2022, 02/07/2022]","[02/06/2022, 06/07/2022]","[$ 1100,0 reais, $ 2600,0 reais]"
2,B201 (blocoAP),"[03/06/2022, 03/07/2022]","[07/06/2022, 03/07/2022]","[$ 1200,0 reais, $ 2700,0 reais]"
3,B202 (blocoAP),"[04/06/2022, 04/07/2022]","[07/06/2022, 05/07/2022]","[$ 1300,0 reais, $ 2800,0 reais]"
4,C301 (blocoAP),"[05/06/2022, 05/07/2022]","[10/06/2022, 09/07/2022]","[$ 1400,0 reais, $ 2900,0 reais]"

In [4]:
# Prática aula 02
# Remover os dados em listas dentro do DataFrame;
colunas = list(dados.columns)
colunas

['apartamento',
 'datas_combinadas_pagamento',
 'datas_de_pagamento',
 'valor_aluguel']

In [5]:
dados = dados.explode(colunas[1:])
dados

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),01/06/2022,05/06/2022,"$ 1000,0 reais"
0,A101 (blocoAP),01/07/2022,03/07/2022,"$ 2500,0 reais"
1,A102 (blocoAP),02/06/2022,02/06/2022,"$ 1100,0 reais"
1,A102 (blocoAP),02/07/2022,06/07/2022,"$ 2600,0 reais"
2,B201 (blocoAP),03/06/2022,07/06/2022,"$ 1200,0 reais"
2,B201 (blocoAP),03/07/2022,03/07/2022,"$ 2700,0 reais"
3,B202 (blocoAP),04/06/2022,07/06/2022,"$ 1300,0 reais"
3,B202 (blocoAP),04/07/2022,05/07/2022,"$ 2800,0 reais"
4,C301 (blocoAP),05/06/2022,10/06/2022,"$ 1400,0 reais"
4,C301 (blocoAP),05/07/2022,09/07/2022,"$ 2900,0 reais"
5,C302 (blocoAP),06/06/2022,08/06/2022,"$ 1500,0 reais"
5,C302 (blocoAP),06/07/2022,12/07/2022,"$ 1200,0 reais"
6,D401 (blocoAP),07/06/2022,07/06/2022,"$ 1600,0 reais"
6,D401 (blocoAP),07/07/2022,09/07/2022,"$ 1300,0 reais"
7,D402 (blocoAP),08/06/2022,10/06/2022,"$ 1700,0 reais"
7,D402 (blocoAP),08/07/2022,14/07/2022,"$ 1400,0 reais"
8,E501 (blocoAP),09/06/2022,10/06/2022,"$ 1800,0 reais"
8,E501 (blocoAP),09/07/2022,09/07/2022,"$ 1500,0 reais"
9,E502 (blocoAP),10/06/2022,16/06/2022,"$ 1900,0 reais"
9,E502 (blocoAP),10/07/2022,12/07/2022,"$ 1600,0 reais"
10,F601 (blocoAP),11/06/2022,17/06/2022,"$ 2000,0 reais"
10,F601 (blocoAP),11/07/2022,13/07/2022,"$ 1000,0 reais"
11,F602 (blocoAP),12/06/2022,15/06/2022,"$ 2100,0 reais"
11,F602 (blocoAP),12/07/2022,12/07/2022,"$ 1100,0 reais"
12,G701 (blocoAP),13/06/2022,19/06/2022,"$ 2200,0 reais"
12,G701 (blocoAP),13/07/2022,20/07/2022,"$ 1200,0 reais"
13,G702 (blocoAP),14/06/2022,15/06/2022,"$ 2300,0 reais"
13,G702 (blocoAP),14/07/2022,17/07/2022,"$ 2100,0 reais"
14,H801 (blocoAP),15/06/2022,18/06/2022,"$ 2400,0 reais"
14,H801 (blocoAP),15/07/2022,16/07/2022,"$ 2200,0 reais"

In [6]:
dados.reset_index(inplace = True, drop = True)
dados.head()

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),01/06/2022,05/06/2022,"$ 1000,0 reais"
1,A101 (blocoAP),01/07/2022,03/07/2022,"$ 2500,0 reais"
2,A102 (blocoAP),02/06/2022,02/06/2022,"$ 1100,0 reais"
3,A102 (blocoAP),02/07/2022,06/07/2022,"$ 2600,0 reais"
4,B201 (blocoAP),03/06/2022,07/06/2022,"$ 1200,0 reais"

In [7]:
# Verificar os tipos de dados;
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   apartamento                 30 non-null     object
 1   datas_combinadas_pagamento  30 non-null     object
 2   datas_de_pagamento          30 non-null     object
 3   valor_aluguel               30 non-null     object
dtypes: object(4)
memory usage: 1.1+ KB

In [8]:
# Identificar colunas numéricas;
dados['valor_aluguel']

0     $ 1000,0 reais
1     $ 2500,0 reais
2     $ 1100,0 reais
3     $ 2600,0 reais
4     $ 1200,0 reais
5     $ 2700,0 reais
6     $ 1300,0 reais
7     $ 2800,0 reais
8     $ 1400,0 reais
9     $ 2900,0 reais
10    $ 1500,0 reais
11    $ 1200,0 reais
12    $ 1600,0 reais
13    $ 1300,0 reais
14    $ 1700,0 reais
15    $ 1400,0 reais
16    $ 1800,0 reais
17    $ 1500,0 reais
18    $ 1900,0 reais
19    $ 1600,0 reais
20    $ 2000,0 reais
21    $ 1000,0 reais
22    $ 2100,0 reais
23    $ 1100,0 reais
24    $ 2200,0 reais
25    $ 1200,0 reais
26    $ 2300,0 reais
27    $ 2100,0 reais
28    $ 2400,0 reais
29    $ 2200,0 reais
Name: valor_aluguel, dtype: object

In [9]:
dados['valor_aluguel'].apply(lambda x: x.replace('$', '').replace(',','').replace('reais','').strip())

0     10000
1     25000
2     11000
3     26000
4     12000
5     27000
6     13000
7     28000
8     14000
9     29000
10    15000
11    12000
12    16000
13    13000
14    17000
15    14000
16    18000
17    15000
18    19000
19    16000
20    20000
21    10000
22    21000
23    11000
24    22000
25    12000
26    23000
27    21000
28    24000
29    22000
Name: valor_aluguel, dtype: object

In [10]:
dados['valor_aluguel'] = dados['valor_aluguel'].apply(lambda x: x.replace('$', '').replace(',','').replace('reais','').strip())

In [11]:
import numpy as np

In [12]:
dados['valor_aluguel'] = dados['valor_aluguel'].astype(np.float64)
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   apartamento                 30 non-null     object
 1   datas_combinadas_pagamento  30 non-null     object
 2   datas_de_pagamento          30 non-null     object
 3   valor_aluguel               30 non-null     float64
dtypes: float64(1), object(3)
memory usage: 1.1+ KB

**Prática aula 03**

Buscando explicar a organização da identificação dos apartamentos, durante a criação do conjunto de dados, foi adicionado o texto (blocoAP). Esse texto informa que os nomes dos apartamentos estão organizados com a letra do bloco seguida do número do apartamento. No entanto, isso não traz nenhuma informação para nossos dados, sendo interessante realizar a remoção desse texto no conjunto de dados.

Com isso, manipule os textos na coluna apartamento para remover o texto (blocoAP) do DataFrame.

In [13]:
dados['apartamento']

0     A101 (blocoAP)
1     A101 (blocoAP)
2     A102 (blocoAP)
3     A102 (blocoAP)
4     B201 (blocoAP)
5     B201 (blocoAP)
6     B202 (blocoAP)
7     B202 (blocoAP)
8     C301 (blocoAP)
9     C301 (blocoAP)
10    C302 (blocoAP)
11    C302 (blocoAP)
12    D401 (blocoAP)
13    D401 (blocoAP)
14    D402 (blocoAP)
15    D402 (blocoAP)
16    E501 (blocoAP)
17    E501 (blocoAP)
18    E502 (blocoAP)
19    E502 (blocoAP)
20    F601 (blocoAP)
21    F601 (blocoAP)
22    F602 (blocoAP)
23    F602 (blocoAP)
24    G701 (blocoAP)
25    G701 (blocoAP)
26    G702 (blocoAP)
27    G702 (blocoAP)
28    H801 (blocoAP)
29    H801 (blocoAP)
Name: apartamento, dtype: object

In [14]:
# Foi necessário adicionar a barra '\' para ser considerados os parênteses como caracteres literais
dados['apartamento'].str.replace('\(blocoAP\)','',regex=True)

0     A101
1     A101
2     A102
3     A102
4     B201
5     B201
6     B202
7     B202
8     C301
9     C301
10    C302
11    C302
12    D401
13    D401
14    D402
15    D402
16    E501
17    E501
18    E502
19    E502
20    F601
21    F601
22    F602
23    F602
24    G701
25    G701
26    G702
27    G702
28    H801
29    H801
Name: apartamento, dtype: object

In [15]:
dados['apartamento'] = dados['apartamento'].str.replace('\(blocoAP\)','',regex=True)
dados.head()

  apartamento datas_combinadas_pagamento datas_de_pagamento  valor_aluguel
0       A101                  01/06/2022         05/06/2022        10000.0
1       A101                  01/07/2022         03/07/2022        25000.0
2       A102                  02/06/2022         02/06/2022        11000.0
3       A102                  02/07/2022         06/07/2022        26000.0
4       B201                  03/06/2022         07/06/2022        12000.0

Prática aula 04:
Assim como no projeto desafio 1, trabalhamos com todas as colunas exceto as que envolvem datas.

Nas colunas datas_de_pagamento e datas_combinadas_pagamento, temos datas em formato 'dia/mês/ano' (dd/mm/AAAA). Transforme esses dados para o tipo datetime e busque uma forma de visualização de subconjunto que possa contribuir no objetivo do contexto que os dados estão inseridos.

Se você não lembra o problema do projeto desafio 2, vou deixar abaixo o texto da situação para facilitar o encontro da informação:

A administração de condomínios é uma tarefa que requer muita atenção e organização. Entre as diversas responsabilidades da gestão está o recebimento dos aluguéis dos locatários. Para garantir uma boa saúde financeira do empreendimento, é fundamental que esses pagamentos sejam feitos de forma regular e pontual. No entanto, sabemos que nem sempre isso acontece. Pensando nisso, proponho um desafio de tratamento de dados com o objetivo de analisar o atraso no pagamento de aluguéis no condomínio fictício de alguns moradores.

In [16]:
dados

   apartamento datas_combinadas_pagamento datas_de_pagamento  valor_aluguel
0        A101                  01/06/2022         05/06/2022        10000.0
1        A101                  01/07/2022         03/07/2022        25000.0
2        A102                  02/06/2022         02/06/2022        11000.0
3        A102                  02/07/2022         06/07/2022        26000.0
4        B201                  03/06/2022         07/06/2022        12000.0
5        B201                  03/07/2022         03/07/2022        27000.0
6        B202                  04/06/2022         07/06/2022        13000.0
7        B202                  04/07/2022         05/07/2022        28000.0
8        C301                  05/06/2022         10/06/2022        14000.0
9        C301                  05/07/2022         09/07/2022        29000.0
10       C302                  06/06/2022         08/06/2022        15000.0
11       C302                  06/07/2022         12/07/2022        12000.0
12       D401                  07/06/2022         07/06/2022        16000.0
13       D401                  07/07/2022         09/07/2022        13000.0
14       D402                  08/06/2022         10/06/2022        17000.0
15       D402                  08/07/2022         14/07/2022        14000.0
16       E501                  09/06/2022         10/06/2022        18000.0
17       E501                  09/07/2022         09/07/2022        15000.0
18       E502                  10/06/2022         16/06/2022        19000.0
19       E502                  10/07/2022         12/07/2022        16000.0
20       F601                  11/06/2022         17/06/2022        20000.0
21       F601                  11/07/2022         13/07/2022        10000.0
22       F602                  12/06/2022         15/06/2022        21000.0
23       F602                  12/07/2022         12/07/2022        11000.0
24       G701                  13/06/2022         19/06/2022        22000.0
25       G701                  13/07/2022         20/07/2022        12000.0
26       G702                  14/06/2022         15/06/2022        23000.0
27       G702                  14/07/2022         17/07/2022        21000.0
28       H801                  15/06/2022         18/06/2022        24000.0
29       H801                  15/07/2022         16/07/2022        22000.0

In [21]:
import datetime as dt

In [22]:
dados['datas_de_pagamento'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 30 entries, 0 to 29
Series name: datas_de_pagamento
Non-Null Count  Dtype
--------------  -----
30 non-null     object
dtypes: object(1)
memory usage: 372.0+ bytes

In [24]:
## Transformar para o tipo datetime definindo o formato de data como DD/MM/AAAA ('%d/%m/%Y')
pd.to_datetime(dados['datas_de_pagamento'], format= '%d/%m/%Y')
dados['datas_de_pagamento'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 30 entries, 0 to 29
Series name: datas_de_pagamento
Non-Null Count  Dtype
--------------  -----
30 non-null     object
dtypes: object(1)
memory usage: 372.0+ bytes

In [29]:
dados['datas_de_pagamento'] = pd.to_datetime(dados['datas_de_pagamento'], format= '%d/%m/%Y')
dados

   apartamento datas_combinadas_pagamento datas_de_pagamento  valor_aluguel
0        A101                  01/06/2022         2022-06-05        10000.0
1        A101                  01/07/2022         2022-07-03        25000.0
2        A102                  02/06/2022         2022-06-02        11000.0
3        A102                  02/07/2022         2022-07-06        26000.0
4        B201                  03/06/2022         2022-06-07        12000.0
5        B201                  03/07/2022         2022-07-03        27000.0
6        B202                  04/06/2022         2022-06-07        13000.0
7        B202                  04/07/2022         2022-07-05        28000.0
8        C301                  05/06/2022         2022-06-10        14000.0
9        C301                  05/07/2022         2022-07-09        29000.0
10       C302                  06/06/2022         2022-06-08        15000.0
11       C302                  06/07/2022         2022-07-12        12000.0
12       D401                  07/06/2022         2022-06-07        16000.0
13       D401                  07/07/2022         2022-07-09        13000.0
14       D402                  08/06/2022         2022-06-10        17000.0
15       D402                  08/07/2022         2022-07-14        14000.0
16       E501                  09/06/2022         2022-06-10        18000.0
17       E501                  09/07/2022         2022-07-09        15000.0
18       E502                  10/06/2022         2022-06-16        19000.0
19       E502                  10/07/2022         2022-07-12        16000.0
20       F601                  11/06/2022         2022-06-17        20000.0
21       F601                  11/07/2022         2022-07-13        10000.0
22       F602                  12/06/2022         2022-06-15        21000.0
23       F602                  12/07/2022         2022-07-12        11000.0
24       G701                  13/06/2022         2022-06-19        22000.0
25       G701                  13/07/2022         2022-07-20        12000.0
26       G702                  14/06/2022         2022-06-15        23000.0
27       G702                  14/07/2022         2022-07-17        21000.0
28       H801                  15/06/2022         2022-06-18        24000.0
29       H801                  15/07/2022         2022-07-16        22000.0

In [26]:
dados['datas_combinadas_pagamento'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 30 entries, 0 to 29
Series name: datas_combinadas_pagamento
Non-Null Count  Dtype
--------------  -----
30 non-null     object
dtypes: object(1)
memory usage: 372.0+ bytes

In [27]:
pd.to_datetime(dados['datas_combinadas_pagamento'], format= '%d/%m/%Y')
dados['datas_combinadas_pagamento'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 30 entries, 0 to 29
Series name: datas_combinadas_pagamento
Non-Null Count  Dtype
--------------  -----
30 non-null     object
dtypes: object(1)
memory usage: 372.0+ bytes

In [30]:
dados['datas_combinadas_pagamento'] = pd.to_datetime(dados['datas_combinadas_pagamento'], format= '%d/%m/%Y')
dados

   apartamento datas_combinadas_pagamento datas_de_pagamento  valor_aluguel
0        A101                  2022-06-01         2022-06-05        10000.0
1        A101                  2022-07-01         2022-07-03        25000.0
2        A102                  2022-06-02         2022-06-02        11000.0
3        A102                  2022-07-02         2022-07-06        26000.0
4        B201                  2022-06-03         2022-06-07        12000.0
5        B201                  2022-07-03         2022-07-03        27000.0
6        B202                  2022-06-04         2022-06-07        13000.0
7        B202                  2022-07-04         2022-07-05        28000.0
8        C301                  2022-06-05         2022-06-10        14000.0
9        C301                  2022-07-05         2022-07-09        29000.0
10       C302                  2022-06-06         2022-06-08        15000.0
11       C302                  2022-07-06         2022-07-12        12000.0
12       D401                  2022-06-07         2022-06-07        16000.0
13       D401                  2022-07-07         2022-07-09        13000.0
14       D402                  2022-06-08         2022-06-10        17000.0
15       D402                  2022-07-08         2022-07-14        14000.0
16       E501                  2022-06-09         2022-06-10        18000.0
17       E501                  2022-07-09         2022-07-09        15000.0
18       E502                  2022-06-10         2022-06-16        19000.0
19       E502                  2022-07-10         2022-07-12        16000.0
20       F601                  2022-06-11         2022-06-17        20000.0
21       F601                  2022-07-11         2022-07-13        10000.0
22       F602                  2022-06-12         2022-06-15        21000.0
23       F602                  2022-07-12         2022-07-12        11000.0
24       G701                  2022-06-13         2022-06-19        22000.0
25       G701                  2022-07-13         2022-07-20        12000.0
26       G702                  2022-06-14         2022-06-15        23000.0
27       G702                  2022-07-14         2022-07-17        21000.0
28       H801                  2022-06-15         2022-06-18        24000.0
29       H801                  2022-07-15         2022-07-16        22000.0

In [31]:
# Para contribuir na solução do contexto é possível calcular a diferença de dias
# entre a data combinada e a data de pagamento com dt.days

dados['atraso'] = dados['datas_de_pagamento'] - dados['datas_de_pagamento']
dados

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel,atraso
0,A101,2022-06-01,2022-06-05,10000.0,0 days
1,A101,2022-07-01,2022-07-03,25000.0,0 days
2,A102,2022-06-02,2022-06-02,11000.0,0 days
3,A102,2022-07-02,2022-07-06,26000.0,0 days
4,B201,2022-06-03,2022-06-07,12000.0,0 days
5,B201,2022-07-03,2022-07-03,27000.0,0 days
6,B202,2022-06-04,2022-06-07,13000.0,0 days
7,B202,2022-07-04,2022-07-05,28000.0,0 days
8,C301,2022-06-05,2022-06-10,14000.0,0 days
9,C301,2022-07-05,2022-07-09,29000.0,0 days
10,C302,2022-06-06,2022-06-08,15000.0,0 days
11,C302,2022-07-06,2022-07-12,12000.0,0 days
12,D401,2022-06-07,2022-06-07,16000.0,0 days
13,D401,2022-07-07,2022-07-09,13000.0,0 days
14,D402,2022-06-08,2022-06-10,17000.0,0 days
15,D402,2022-07-08,2022-07-14,14000.0,0 days
16,E501,2022-06-09,2022-06-10,18000.0,0 days
17,E501,2022-07-09,2022-07-09,15000.0,0 days
18,E502,2022-06-10,2022-06-16,19000.0,0 days
19,E502,2022-07-10,2022-07-12,16000.0,0 days
20,F601,2022-06-11,2022-06-17,20000.0,0 days
21,F601,2022-07-11,2022-07-13,10000.0,0 days
22,F602,2022-06-12,2022-06-15,21000.0,0 days
23,F602,2022-07-12,2022-07-12,11000.0,0 days
24,G701,2022-06-13,2022-06-19,22000.0,0 days
25,G701,2022-07-13,2022-07-20,12000.0,0 days
26,G702,2022-06-14,2022-06-15,23000.0,0 days
27,G702,2022-07-14,2022-07-17,21000.0,0 days
28,H801,2022-06-15,2022-06-18,24000.0,0 days
29,H801,2022-07-15,2022-07-16,22000.0,0 days

In [32]:
# Calcular a média de tempo de atraso por apartamentos
media_atraso = dados.groupby(['apartamento'])['atraso'].mean()
# Visualizar o resultado
media_atraso

apartamento
A101    0 days
A102    0 days
B201    0 days
B202    0 days
C301    0 days
C302    0 days
D401    0 days
D402    0 days
E501    0 days
E502    0 days
F601    0 days
F602    0 days
G701    0 days
G702    0 days
H801    0 days
Name: atraso, dtype: timedelta64[ns]